stages:
  - build
  - deploy

build_app:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest ./app
    - docker push $CI_REGISTRY_IMAGE:latest
  tags:
    - docker

deploy_to_k8s:
  stage: deploy
  image: alpine
  script:
    - echo "This is a placeholder for deployment."
    - echo "In a real environment, this job would use kubectl to apply the k8s manifests."
    - echo "For this project, deployment is handled via the Ansible playbook."
  # Requires a self-hosted GitLab runner with kubectl configured. Under costruction.