apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  replicas: 2 # Run 2 copies of our app
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: web-server
        image: ivan_tulskii/kube-mini-cloud:latest
        imagePullPolicy: IfNotPresent # We will build this image
        ports:
        - containerPort: 5000